version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular"
  ]
  environment = [
    "browser",
    "nodejs"
  ]

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "php"

[[analyzers]]
name = "sql"